spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.200:3306/tt_easy_slave?useUnicode=true&autoReconnect=true
    username: root
    password: harrison@onfresh.cn
    druid:
      initial-size: 3
      max-active: 10
      min-idle: 1
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 10
      #等价于上面的max-pool-prepared-statement-per-connection-size
      max-open-prepared-statements: 10
      validation-query: select 1 from dual
      validation-query-timeout: 3000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      max-evictable-idle-time-millis: 6000
      min-evictable-idle-time-millis: 3000

  redis:
    database: 0
    host: 192.168.204.200
    port: 6379
    password:
    timeout: 50000
    jedis:
      pool:
        max-active: 50 #最大连接数
        max-idle: 20 #最大空闲连接数
        max-wait: -1 #最大等待时间
        min-idle: 0 #初始化连接数
        shutdown-timeout: 100
  zipkin:
    base-url: http://localhost:9411
zk:
  host: 116.62.149.88:8181
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
